//! hex_blob_autotile_flat — **full 64-tile** flat-top hex autotiling (`TilemapAutotile::hex_6_flat`).
//!
//! The flat-top (odd-q) twin of `hex_blob_autotile`: a contiguous 64-tile atlas where tile `mask`
//! draws a hexagon outlined on exactly the edges whose neighbor is absent, so every open side is
//! bordered correctly. Pairs `TilemapProjection::HexagonalFlat` with `Neighborhood::Hex6Flat`. The
//! atlas is generated by `cargo run --example gen_hex_autotile_sheet` (tile index == the
//! `Hex6Flat` mask: N=1, S=2, NE=4, SE=8, NW=16, SW=32).
//!
//! Run from the repo root:  `cargo run --example hex_blob_autotile_flat`
//! Arrows = move cursor · Space = dig/fill the cell · ESC = quit.

use engine::{
    App, Color, DrawText, InputState, KeyCode, ShouldQuit, System, TextQueue, Tilemap,
    TilemapAtlas, TilemapAutotile, TilemapProjection, TilemapSystem, Vec2, ViewportSize,
    WindowConfig, World,
};

const ROWS: usize = 9;
const COLS: usize = 9;
const FILLED: u32 = 1; // any non-zero connects (single terrain)

/// Moves a cursor and digs/fills the hovered hex; the rest is the engine's reactive autotiling.
struct DigControl {
    map: engine::Entity,
    sel: (usize, usize),
}

impl System for DigControl {
    fn run(&mut self, world: &mut World, _dt: f32) {
        let (mut dr, mut dc, mut dig, mut quit) = (0i32, 0i32, false, false);
        if let Some(input) = world.resource::<InputState>() {
            if input.just_pressed(KeyCode::ArrowUp) {
                dr -= 1;
            }
            if input.just_pressed(KeyCode::ArrowDown) {
                dr += 1;
            }
            if input.just_pressed(KeyCode::ArrowLeft) {
                dc -= 1;
            }
            if input.just_pressed(KeyCode::ArrowRight) {
                dc += 1;
            }
            dig = input.just_pressed(KeyCode::Space);
            quit = input.just_pressed(KeyCode::Escape);
        }
        if quit {
            if let Some(q) = world.resource_mut::<ShouldQuit>() {
                q.quit();
            }
        }
        if dr != 0 || dc != 0 {
            self.sel.0 = (self.sel.0 as i32 + dr).clamp(0, ROWS as i32 - 1) as usize;
            self.sel.1 = (self.sel.1 as i32 + dc).clamp(0, COLS as i32 - 1) as usize;
        }
        if dig {
            if let Some(tm) = world.get_mut::<Tilemap>(self.map) {
                let cur = tm.get_tile(self.sel.0, self.sel.1).unwrap_or(0);
                tm.set_tile(self.sel.0, self.sel.1, if cur == 0 { FILLED } else { 0 });
            }
        }

        let vh = world
            .resource::<ViewportSize>()
            .map(|v| v.height)
            .unwrap_or(600.0);
        if let Some(tq) = world.resource_mut::<TextQueue>() {
            tq.push(DrawText::new(
                "Hex blob autotile (Hex6Flat, 64 tiles) — Arrows: move · Space: dig/fill · ESC: quit",
                Vec2::new(20.0, 20.0),
                18.0,
                Color::rgb(0.75, 0.82, 0.95),
            ));
            tq.push(DrawText::new(
                format!(
                    "cursor (row, col) = {:?}  (flat-top: every open hex edge is outlined by its mask tile)",
                    self.sel
                ),
                Vec2::new(20.0, vh - 40.0),
                18.0,
                Color::rgb(0.95, 0.85, 0.55),
            ));
        }
    }

    fn name(&self) -> &'static str {
        "hex_blob_flat_dig_control"
    }
}

/// A solid field with a few carved holes, so the opening screen already exercises many of the 64
/// mask tiles (rim + interior holes), not just the all-neighbors tile.
fn carved_field() -> Vec<Vec<u32>> {
    let mut tiles = vec![vec![FILLED; COLS]; ROWS];
    for (r, c) in [
        (2, 2),
        (2, 3),
        (3, 2),
        (4, 5),
        (5, 5),
        (6, 3),
        (6, 6),
        (3, 6),
    ] {
        tiles[r][c] = 0;
    }
    tiles
}

fn main() {
    let mut app = App::new();
    app.world.insert_resource(WindowConfig {
        title: "hex_blob_autotile_flat — Hex6Flat 64-tile blob autotiling".to_string(),
        width: 900,
        height: 700,
        clear_color: [0.06, 0.07, 0.10, 1.0],
    });

    // The 64-tile flat-top blob sheet (8×8): tile index == Hex6Flat neighbor mask.
    app.load_image("examples/assets/hex_autotile_flat.png");
    let atlas = TilemapAtlas::new("examples/assets/hex_autotile_flat.png", 8, 8);

    // Identity mask→tile map (tile 0 + mask) — the whole point of the blob sheet.
    let autotile = TilemapAutotile::hex_6_flat(0);

    let tilemap = Tilemap::new(atlas, carved_field(), 72.0, Vec2::new(170.0, 120.0))
        .with_projection(TilemapProjection::HexagonalFlat);

    let map = app.world.spawn();
    app.world.add_component(map, tilemap);
    app.world.add_component(map, autotile);

    app.add_system(TilemapSystem::new());
    app.add_system(DigControl {
        map,
        sel: (ROWS / 2, COLS / 2),
    });
    app.run();
}
